### ISSUE TITLE
Subtracting 2 cubes doesn't work due to a typo

### ISSUE THREAD

**Issue by drmewes** [funkymunkycool/Cube-Toolz#1]
The typo is in the definition of the diff function (line 287 in cube_tools.py). 

Its defined as
def diff1_cubes(files):
but called as
diff_cubes(files):

Aligning the definition solves the problem. Also the results are correct.

Cheers,
Jan

**Comment by funkymunkycool** [comment]
Thank you. I have fixed this now! Should be working
