### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by vladislavivanistsev** [funkymunkycool/Cube-Toolz#11]
I get and warning with python 3.10 and numpy 3.22

cube_tools.py:265: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
ZYX = ZYX * dZYX

**Comment by funkymunkycool** [comment]
This warning is harmless. However, the latest commit has now fixed this issue. Try pulling the latest version.
