### ISSUE TITLE
couldn't activate the code

### ISSUE THREAD

**Issue by varesh110** [funkymunkycool/Cube-Toolz#2]
Dear Tassem El-Sayed,
I couldn't use the code, after I write e.g : "python2.7 cube_tools.py [-i INTEGRATE]  Files [4.cube]" command in terminal, without any error ! but nothing happen! 
I would be grateful if yo can advice me about, 
looking forward to receiving your valuable comments on my problem.
B.R
Fatemeh

**Comment by funkymunkycool** [comment]
Dear Fatemeh,

To integrate around an atom, you can use the following command...
python cube_tools.py -ia 13 4 file.cube

In this case, the code will integrate a sphere around atom number 13 with a radius of 4 Angstrom.

Hope this helps.

Thanks,
Tassem
