### ISSUE TITLE
Plane average in z direction

### ISSUE THREAD

**Issue by maksimovdmitrii** [funkymunkycool/Cube-Toolz#3]
Is it a typo in line 180:        
elif axis == 'z':
            xy_area=np.linalg.norm(np.cross((self.NY*self.Y*bohrM),(self.NX*bohrM*self.X)))
            PlanAv=np.array([[nz*self.Z[2]*bohrA,np.sum(**self.data[nz]**)/(self.NY*self.NZ)] for nz in xrange(self.NZ)])

instead of:

        elif axis == 'z':
            xy_area=np.linalg.norm(np.cross((self.NY*self.Y*bohrM),(self.NX*bohrM*self.X)))
            PlanAv=np.array([[nz*self.Z[2]*bohrA,np.sum(self.data[:,:,nz])/(self.NY*self.NZ)] for nz in xrange(self.NZ)])

**Comment by funkymunkycool** [comment]
Indeed this is a typo. Thanks, Nice spot!

Fixed now.
